name: Sync Folders to Another Repo

on:
  push:
    branches: [ main ]  # 或你需要同步的分支
  workflow_dispatch:  # 手动触发

jobs:
  sync-md-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show workspace structure
        run: |
          pwd
          ls -l

      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: Navyum/Knowledge   # 修正仓库名称大小写
          token: ${{ secrets.TARGET_REPO_TOKEN }}  # 需要在主仓库设置此 secret
          path: Knowledge
          persist-credentials: false

      - name: Show workspace structure
        run: |
          ls -l
          ls -l Knowledge

      - name: Sync folders (force overwrite, keep dot folders)
        run: |
          # 递归删除所有非.开头的文件夹
          find Knowledge -maxdepth 1 -type d ! -name '.' ! -name '.*' -exec rm -rf {} +
          ls -l 
          # 复制主仓库的docs目录下的符合规则的文件夹到目标仓库
          DIRS=($(find docs -mindepth 1 -maxdepth 1 -type d ! -name '.' ! -name '.*' ! -name '_*' -printf '%f\n'))
          echo "DIRS: ${DIRS[@]}"
          for d in "${DIRS[@]}"; do
            cp -r "docs/$d" Knowledge/
          done
          ls -l 

      - name: Commit & Push to target repo
        run: |
          cd Knowledge
          git add -A
          git commit -m "[sync] Force update from source repo" || exit 0
          echo ${{ secrets.TARGET_REPO_TOKEN }}
          git remote set-url origin https://${{ secrets.TARGET_REPO_TOKEN }}@github.com/Navyum/Knowledge.git
          git push origin main
